### PR TITLE
add doc for functional tests + github workflow

### PR DESCRIPTION
**Pull request by rgildein**
blocked by #34

### CODE REVIEW

**Review by rgildein — COMMENTED** [review]
recheck-snap

**Comment by jneo8** [comment]
There is a `Error: Process completed with exit code 128` in the checks.

**Review by jneo8 — CHANGES_REQUESTED** [review]
There is a `Error: Process completed with exit code 128` in the checks.

**Review by esunar — APPROVED** [review]
Overall ok. My only suggestion is to add examples also with Makefile.

**Comment by rgildein** [comment]
> There is a `Error: Process completed with exit code 128` in the checks.

Yes, because we are using main and not master. Thanks I'll update it.

**Review by rgildein — COMMENTED** [review]
recheck

**Review by rgildein — COMMENTED** [review]
recheck

**Review by rgildein — COMMENTED** [review]
recheck

**Review by rgildein — COMMENTED** [review]
recheck

**Pull request merged**
